## Linear Algebra

We understand the importance of vectors, matrics and tensors and how to perform algebraic operations on them. Also, some relevant mathematical operations that will come handy during model preparation and training

In [10]:
import torch
x, y = torch.tensor(2), torch.tensor(3.)
print(x, y) # Scalar

x = torch.arange(3)
print(x, x.shape) # Vectors

X = torch.arange(6).view((2,3))
print(X) # Matrics

X_transpose = X.T
print(X_transpose) # X_transpose_ij = X_ji

X = torch.arange(24).view((2,3,4))
print(X) # Tensor



tensor(2) tensor(3.)
tensor([0, 1, 2]) torch.Size([3])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### Reduction and Non-Reduction of Tensor

We can reduce the tensor along any axis with `sum()` function. Also, we can sum only along a particular axis and not reduce it completely.

The `keepdims` parameter keeps the dimensions along differents axes, this helps when we want to normallize along some direction.

In [18]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [32]:
A = torch.arange(6, dtype=torch.float32).view((2,3))
A, A.sum(), A.sum(axis=0), A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.),
 tensor([3., 5., 7.]),
 tensor([ 3., 12.]))

In [33]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape, A/sum_A # Using A/sum_A we were able to make the sum of all elements = 1 by using keepdims

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

### Dot Product and Cross Products

In [34]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [35]:
B = torch.ones(3, 4)
A@B

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

### Exercise