# Custom Layers

In [12]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

- There are two types of layers:
  - Layers with parameters
  - Layers without parameters

In [2]:
# Layer without parameters
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [5]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [9]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

In [22]:
# Layers with parameters
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn((in_units, units)))
        self.bias = nn.Parameter(torch.randn((units, )))

    def forward(self, X):
        return F.relu(torch.matmul(X, self.weight) + self.bias)

In [23]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.0034,  0.8847, -0.5413],
        [-0.3851,  1.1549, -1.2368],
        [-2.0569,  0.0365,  1.3508],
        [-1.4379,  0.1942,  0.5164],
        [-0.2103,  0.6267,  0.9773]], requires_grad=True)

In [24]:
linear(torch.rand(2, 5))

tensor([[0.0000, 2.1792, 0.0000],
        [0.0000, 2.8481, 0.0000]], grad_fn=<ReluBackward0>)

In [48]:
net = nn.Sequential(MyLinear(64, 10), MyLinear(10, 1))
net(torch.rand(2, 64))

tensor([[20.1299],
        [14.4841]], grad_fn=<ReluBackward0>)